language: kotlin
sudo: required
dist: trusty

jdk:
- oraclejdk8

stages:
- name: unblock
  if: type == pull_request
- name: deploy
  if: branch = master AND type != pull_request

env:
  global:
  - JAVA_OPTS="-Xms512m -Xmx1024m"

jobs:
  include:
  - stage: unblock
    script: echo "Unblock PR"
  - stage: deploy
    script:
    - ./gradlew clean build
    - ./deploy-scripts/deploy.sh
